version: '3.7'

services:
  react-crud:
    container_name: react-crud
    build:
      context: ../
      dockerfile: ./deploy/dockerfile
    volumes:
      - '../code:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true